### ISSUE TITLE
Descriptions truncated

### ISSUE THREAD

**Issue by dmoulton** [bramwaas/wordpress-plugin-wsa-simple-google-calendar-widget#1]
The descriptions of my calendar items are being truncated fairly early. I'd like to show more of them before cutting off. Is this possible?

**Comment by bramwaas** [comment]
Hi David, thank you for your comment. I did not know my code truncated the description.
After your comment I found that after 63 characters the Description is divided in lines of  76 characters and I only use the first line.
Similar the Summary is split after 66 characters.
I think I have found a solution to display all lines of the Description, Summary and Location and uploaded it as V1.0.2.
Regards Bram

**Comment by dmoulton** [comment]
This works great, thanks!
