### ISSUE TITLE
Recurring events computed incorrectly

### ISSUE THREAD

**Issue by peppergrayxyz** [bramwaas/wordpress-plugin-wsa-simple-google-calendar-widget#19]
Hi, 

I have an issue with recurring events: 

The event (starting on Oct. 26th, see below) should repeat on every last Wednesday of the month, but instead it repeats weekly.

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Venib (calshare)
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VTIMEZONE
TZID:Europe/Vienna
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20220904T162143Z
DTSTAMP:20220904T162404Z
LAST-MODIFIED:20220904T162404Z
SEQUENCE:3
UID:da0c941d-5a57-43ac-948e-06bb93111d4a
DTSTART;TZID=Europe/Vienna:20221026T180000
DTEND;TZID=Europe/Vienna:20221026T200000
STATUS:CONFIRMED
SUMMARY:Meeting
LOCATION:Place
DESCRIPTION:Text
RRULE:FREQ=MONTHLY;BYDAY=WE;BYSETPOS=-1
END:VEVENT
END:VCALENDAR
```

The export is from NextCloud calendar, there it is displayed correctly. Output from the plugin:

![grafik](https://user-images.githubusercontent.com/111446242/189079672-2085d3a8-c74e-4ec6-8ec5-40f46d25d672.png)

**Comment by bramwaas** [comment]
Thank you for your test and the clear example.
I see a BYSETPOS=-1 in the rrule that is not parsed. Probably BYDAY=-1WE would give the expected result.

I will look in the ical standards how BYSETPOS should be interpreted and if that is clear to me parse it in the next version. If it is easy I can release it before the end of september. If it is more difficult I will report it in this issue.

Regards Bram

**Comment by bramwaas** [comment]
Version 2.1.0 released.
BYSETPOS is now supported.
I hope this solved your issue.

Regards Bram

Output of your ical example (english with default settings except Number of days ... = 102) :
![peppergrayxyz 2 1 0](https://user-images.githubusercontent.com/11373174/190995829-c592af5b-cc4f-44e7-9137-d7a84820132e.png)

**Comment by peppergrayxyz** [comment]
Thank you very much, everything works fine now!

**Comment by bramwaas** [comment]
Good to hear that.
Then I close this issue.
