### ISSUE TITLE
Recurring event that shouldn't be on the calendar

### ISSUE THREAD

**Issue by dmoulton** [bramwaas/wordpress-plugin-wsa-simple-google-calendar-widget#2]
I am seeing an event in the widget that isn't on my calendar. It's a recurring event. I have been looking at the code and the calendar feed, but I haven't been able to figure it out.

You can see an example of the problem at:

http://uvac.us

BTW I've modified the output format of the plugin a little bit. 

The widget is in the right column. There is currently a meeting there on June 12. That is the event that isn't on the calendar. Here is a link to the calendar:

https://calendar.google.com/calendar/embed?src=utahvalleyastronomyclub%40gmail.com&ctz=America%2FDenver

Here is a link to the ical feed:

https://calendar.google.com/calendar/ical/utahvalleyastronomyclub%40gmail.com/public/basic.ics

I'll keep looking at this, but I wanted to show you before it disappeared from the schedule.

**Comment by bramwaas** [comment]
Hi David, 
Thank you for your comment.
I have copied your ical-feed as a file to my test website.
I found the event that is displayed the 12th juni in the ical feed (the basic.ics) file.
It is een event that is scheduled at 10th of may 2018 and has a recurrence every 2th of the month and not ending.
I think it should indeed never appear in the list because the tenth is not a second day of a month. 
I have no solution yet, but I will work on it. In the meantime I hope you can find the item with this info in your google calendar and delete it there.

Best regards Bram

Here the event that should not be on the calendar:

```
BEGIN:VEVENT
DTSTART;TZID=America/Denver:20180510T190000
DTEND;TZID=America/Denver:20180510T203000
RRULE:FREQ=MONTHLY;BYDAY=2TH
EXDATE;TZID=America/Denver:20190509T190000
EXDATE;TZID=America/Denver:20190214T190000
DTSTAMP:20190529T090102Z
UID:162llisfapcrvn0d708psq6oho_R20180511T010000@google.com
CREATED:20180205T195654Z
DESCRIPTION:The monthly meeting of the Utah Valley Astronomy Club. Details 
 to be announced.
LAST-MODIFIED:20180418T000132Z
LOCATION:Planetarium\, Utah Valley University\, 800 W University Pkwy\, Ore
 m\, UT 84058\, USA
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:UVAC Monthly Meeting
TRANSP:OPAQUE
END:VEVENT
```

**Comment by bramwaas** [comment]
After closer looking at the specification, RRULE:FREQ=MONTHLY;BYDAY=2TH
 means every month second thursday never ending. So it should display the 13th of juni, as it does in my test website. I live in Amsterdam and our timezone is closer to UTC so there will be an error in timezone-interpretation.

I also see two lines with EXDATE (Exception Date-Times) that are not evaluated by my code, but those days are in the past.

**Comment by bramwaas** [comment]
Solved the timezone-issue.
New code uploaded as v1.0.3.
I expect the event wil now display at Thursday 13th of juni at 19h00 till 20h30 in the Denver timezone.
In my opinion that is correct.  But maybe I overlook a (technical) reason why it should not display.

Also made a correction for multiline descriptions etc. In this example I will keep the space in the description between Details and to.
