### ISSUE TITLE
Event title, link destination?

### ISSUE THREAD

**Issue by fhennies** [bramwaas/wordpress-plugin-wsa-simple-google-calendar-widget#6]
Hej,

the event title is formatted as a link to http://[myURL]/#simple_ical_widget-2_79_[randomID]
Is there any place to format/ change this to something useful?

Thanks for the widget!

**Comment by bramwaas** [comment]
Hi Franz,

Thank you for your comment.

We can disagree about the usefulness of the link, but the intention is to use the collapse function of bootstrap and this link to make the details of the appointment (invisible at the start) visible. See:
[https://getbootstrap.com/docs/4.3/components/collapse/](url)

Of course this only works if you use bootstrap, or a similar javascript / css collapse functionality in your theme. If not then I understand that you find the link useless. But I don't know any alternative for where I can get the necessary information from the ical appointment, so I'm open to suggestions.

Regards,
Bram Waasdorp.

**Comment by fhennies** [comment]
Hej Bram,

thanks for the quick answer. Well, that makes sense. I don't have a good proposal. But your answer helped me, and now I just disabled the link with some extra CSS for my template.
