### ISSUE TITLE
Event description, avoid translation of tags into &lt; etc?

### ISSUE THREAD

**Issue by fhennies** [bramwaas/wordpress-plugin-wsa-simple-google-calendar-widget#7]
Hej,

I have a calendar event from google calendar with a html tag in it (`<a>`), when imported the angle brackets get converted to `&lt;` etc. and the html is "disabled". Is there a way to avoid this?

**Comment by bramwaas** [comment]
Hi Franz,

It needs a change in the code to make that possible.

After a question of @justmigrating in the worpress support forum who in my opinion seemed to use the calendar as an editing tool for her Wordpress site 
[https://wordpress.org/support/topic/limit-description-length-2/](https://icalendar.org/)
I have added the following text to my readme.txt:

> = Can I use HTML in the description of the appointement? =
> 
> You can use HTML in the most Calendars, but the result in the plugin may not be what you expect.First most calendars will only give the plain text in the Description in the iCal output.Secondly this plugin filters the HTML to convert characters that have special significance in HTML to the corresponding HTML-entities. So if you manage to get the HTML in the description the output wil not be what you expect.In case you have all kinds of HTML in your appointments a plugin that uses the API of te calendar-application might be a better choice for you. 
> 

However
It is not very difficult to make an option: to skip the  htmlspecialchars function, or (and)  to add a html_entity_decode() function to the description. If that helps you I will do that.

Maybe this will be a solution for this issue, but surely not for all issues with code that is not visible in the description, because as far as I know HTML code should not be included in the standard Description field see quote below.

To use the X-ALT-DESC field if available is a bigger operation.

from [https://icalendar.org/](https://icalendar.org/)

 > The original iCalendar standard allowed only plain text as part of an event description.  HTML markup, such as font attributes (bold, underline) and layout (div, table) was not allowed in the text description field.  First seen in Microsoft Outlook, the X-ALT-DESC parameter provides a method to add HTML to an event description.  "X-" fields are allowed for [non-standard, experimental parameters](https://icalendar.org/iCalendar-RFC-5545/3-2-property-parameters.html). This field has become the method of choice when including HTML in a description.  When using HTML, both fields must be included so that iCalendar readers that do not support the X-ALT-DESC field can still read the text version.

Regards 
Bram Waasdorp

**Comment by fhennies** [comment]
Hi Bram,

thanks for the explanation. 
Google calendar uses html in the DESCRIPTION , framed with `<html-blob>` as soon as you add a link and edit that link with a link text or use html in the description. Google doesn't have X-ALT-DESC, as I can see it.  

To have an option to skip the htmlspecialchars function would help my use case, where I want to be able to have links in the event widget for event details.

**Comment by bramwaas** [comment]
Hi Franz,

ok I will start with optional removing the htmlspecialchars() function.
Tomorrow I will report the status back.

Regards Bram

**Comment by bramwaas** [comment]
Hi Franz,

in Develop on github  I have made some adaptations in files simple-google-icalendar-widget.php and includes/ical.php:
- added a checkbox "Allow safe html in description and summary" to the admin form.
- removed htmlspecialchars function when this box is checked.
- added wp_kses() function to output for decription, summary and location, to output only html that is considered save for posts, and so keep some security against XSS.

Done a preliminary test with the following description and results (see below).
Merged this with the master brache on github.
After some more testing and update documentation I think I will this upload as release 1.5.0 in the Wordpress plugin directory next weekend.

Regards Bram

`DESCRIPTION:Hier <a href="xxx">link</a>hrijving van test afspraak 2.\nHier \n
 <html-blob><a href="xxx">link in blob</a></html-blob>est regel 3.\n
 Hier een uitgeb\n
 reide <script>script</script> test afspraak 2 regel 4.\n`

Result in source with box unchecked (same as before):

`Hier &lt;a href=&quot;xxx&quot;&gt;link&lt;/a&gt;hrijving van test afspraak 2.<br>Hier <br>&lt;html-blob&gt;&lt;a href=&quot;xxx&quot;&gt;link in blob&lt;/a&gt;&lt;/html-blob&gt;est regel 3.<br>Hier een uitgeb<br>reide &lt;script&gt;script&lt;/script&gt; test afspraak 2 regel 4.<br>
`

Result in source with box checked (as expected, link remained intact, insecure script tag is deleted unknown html blob tag is also deleted) :

`Hier <a href="xxx">link</a>hrijving van test afspraak 2.<br>Hier <br><a href="xxx">link in blob</a>est regel 3.<br>Hier een uitgeb<br>reide script test afspraak 2 regel 4.<br>
`

**Comment by bramwaas** [comment]
Hi Franz,

Released version 1.5.0  (also) in WP plugin directory with option "Allow safe html in description and summary." default unchecked.

Regards,
Bram.

**Comment by fhennies** [comment]
Hi Bram,

thank you so much. I will test and implement it tomorrw.

**Comment by fhennies** [comment]
Hi Bram,

thank you so again so much. I have tested and implemented it and it works as I wished for!
